name: Sitemap status check

on:
  workflow_dispatch:
  schedule:
    - cron: "17 1,5,9,13,17,21 * * *"

permissions:
  contents: read

jobs:
  validate-trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow trigger is valid"
